global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: [alertmanager:9093]

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]

  - job_name: grafana
    static_configs:
      - targets: [grafana:3000]

  - job_name: pulseboard-api
    static_configs:
      - targets: [pulseboard-api:8080]
    relabel_configs:
      - target_label: service
        replacement: pulseboard-api

  - job_name: pulseboard-consumer
    static_configs:
      - targets: [pulseboard-consumer:9102]
    relabel_configs:
      - target_label: service
        replacement: pulseboard-consumer
