name: pulseboard-api CI

on:
  push:
    branches: [main]
    paths: ["apps/pulseboard-api/**"]
  pull_request:
    branches: [main]
    paths: ["apps/pulseboard-api/**"]

jobs:
  ci:
    uses: ./.github/workflows/python-app-ci.yml
    permissions:
      checks: write
      contents: read
    with:
      app-name: pulseboard-api
      working-directory: apps/pulseboard-api
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
