name: pulseboard-shared CI

on:
  push:
    branches: [main]
    paths: ["apps/lib/**"]
  pull_request:
    branches: [main]
    paths: ["apps/lib/**"]

jobs:
  ci:
    uses: ./.github/workflows/python-app-ci.yml
    permissions:
      checks: write
      contents: read
    with:
      app-name: pulseboard-shared
      working-directory: apps/lib
      coverage-source: pulseboard_shared
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
